/* Words1000.h */

#ifndef _WORDS1000_H_
#define _WORDS1000_H_

char words1000[] = "hang holistic oceanic development decorous fence question songs chase relation adamant guitar writer ruthless "
"harass unnatural invite bite aloof numberless answer yam carriage apparatus graceful wonderful demonic gruesome "
"imaginary bewildered hypnotic deer therapeutic nasty relax righteous apathetic wrong mother clever impress mix harm "
"aspiring hook drip frog fairies workable mass monkey key sneeze window chunky ambiguous ice well-off matter thoughtful "
"number cure messy frame mere fax cheat shoes voiceless alert kind woozy impulse wander kick beds elated drop north babies "
"cumbersome sense theory note calculator yummy paper enormous drink slope agreement jump incredible oafish aboriginal deeply "
"animal pump cooperative kittens letters support pies connection excellent peaceful fertile lavish efficacious office "
"statement puncture many tin good overwrought believe rush remarkable keen abounding uncle aromatic tight dizzy taste lumber "
"cars obey stitch poke embarrass hard-to-find glossy grumpy fortunate fire elderly puny repeat jumpy erect ignorant tongue "
"fine oranges rejoice madly border squirrel equable baseball size zoo umbrella belong hole mountain cake volatile hungry "
"flesh attract tumble advice vague unequal narrow victorious optimal pushy trashy hop blush warn earthquake houses undesirable "
"harmonious same punch motionless allow children color homely large subsequent instruct flowery stretch property advertisement "
"page straight frightening glistening joyous high-pitched ticket reading dream can uncovered low unbecoming chivalrous belief "
"pretty nose crush refuse fence stew blot colour envious wandering oven art famous witty two hard kaput cat move delightful "
"memorize berserk inject wise kind monkey flow release industrious substantial rainy last agreeable wealth celery choke protect "
"existence pick far-flung ruddy fire trick knee humor mess up occur grade back nail help zonked spare crowd right sail left "
"stare crooked instrument night recondite subdued pray deadpan knotty locket creator pastoral plausible ambiguous rest nondescript "
"fowl unused macabre innate push torpid educated penitent chase governor plantation debonair irate faint crawl thundering judicious "
"righteous sleep bury mind button wax effect afterthought pushy radiate tender glass business stale filthy tranquil jellyfish "
"rule gaping finicky fall suggestion diligent sordid bless gate grey whole eight willing scratch houses hall north notice "
"distribution song nasty amazing fax card fog pie whip utter troubled cause gifted paddle difficult fish bee engine enchanting "
"ring familiar glove design save medical mark obeisant functional yam likeable kneel desire ossified toe subtract maniacal analyze "
"long-term run available enter alive vulgar grouchy thinkable pan fragile laughable quarrelsome tasty money finger tongue confuse "
"beam calculator return industry gratis whine neighborly coherent prevent past haircut flame gaze reading dream can uncovered "
"low unbecoming chivalrous belief pretty nose crush refuse fence stew blot colour envious wandering oven art famous witty two "
"hard kaput cat move delightful memorize berserk inject wise kind monkey flow release industrious substantial rainy last agreeable "
"wealth celery choke protect existence pick far-flung ruddy fire trick knee humor mess up occur grade back nail help zonked spare "
"crowd right sail left stare crooked instrument night recondite subdued pray deadpan knotty locket creator pastoral plausible "
"ambiguous rest nondescript fowl unused macabre innate push torpid educated penitent chase governor plantation debonair irate "
"faint crawl thundering judicious righteous sleep bury mind button wax effect afterthought pushy radiate tender glass business "
"stale filthy tranquil jellyfish rule gaping finicky fall suggestion diligent sordid bless gate grey whole eight willing scratch "
"houses hall north notice distribution song nasty amazing fax card fog pie whip utter troubled cause gifted paddle difficult fish "
"bee engine enchanting ring familiar glove design save medical mark obeisant functional yam likeable kneel desire ossified toe "
"subtract maniacal analyze long-term run available enter alive vulgar grouchy thinkable pan fragile laughable quarrelsome tasty "
"money finger tongue confuse beam calculator return industry gratis whine neighborly coherent prevent past haircut flame gaze "
"yak delay duck confuse wave subdued trot cumbersome burst rainy bang dysfunctional remain lyrical yummy red fluttering plucky "
"winter scandalous grotesque celery nimble powder spiffy hope fabulous terrible interrupt diligent daffy watch short flash ambiguous "
"distinct geese offend scarecrow jump quaint inquisitive hysterical wide bait wax wish children tap infamous pale flagrant "
"unbecoming rescue canvas cast harass snails person distance succinct watery curious familiar lonely oatmeal approve spell meddle "
"kettle vein plausible jazzy quicksand hard object luxuriant instinctive approval important spill bitter fixed level gusty concern "
"courageous argument name hydrant gruesome fireman mellow invite woozy risk quarter zoo bed rigid insurance puzzling amusement "
"spooky weather authority bite sincere scale quince grouchy left song aware wretched ear magenta story blue holiday sudden "
"direction friendly gray earn befitting cap fall suggestion regular tumble park slip jeans stomach warn appliance pink false "
"double airport cheer glib demonic hollow teeny-tiny year dance advertisement tub brown thankful chicken book attend crook "
"saw wry entertaining pets spurious chess wood uninterested macho lacking hands stingy fuzzy super error clover agreement erratic "
"explain drip four finger condemned creature spade root downtown materialistic concerned decide bat mate silly breathe psychotic "
"stiff phobic front disarm rob pop health assorted public known clean lunchroom cause scissors dynamic tearful scene range "
"elite outgoing giraffe payment seat acrid trees entertain rabid north sidewalk song cloth tasty grotesque icky stew grip cherry "
"mighty push hushed short ashamed plate teeny-tiny sparkle lopsided spoon shelf release puffy abaft record deeply zephyr found "
"lame rude colorful advise kill border big line slim unhealthy bake love unique crash hospitable warn vast picture oatmeal "
"harbor ill crazy orange expensive afford whimsical scream ship sudden relieved grubby last add blind zealous obsequious screw "
"jar science throat answer daughter annoyed riddle itchy questionable throne shiny confused vulgar squirrel jaded vivacious "
"cute snow order chief smash wing night defeated murky keen hesitant neat believe rampant lake voyage bubble tick current "
"quarter dirty blot wander care rambunctious spoil scary treatment trashy mine expect trick laughable undress rub selective "
"channel delay hammer overconfident quince craven befitting colour arch mask knit jumpy bouncy psychotic belligerent stare "
"understood freezing milky long accidental attach hot discreet ready house string maddening loutish spurious door birthday gabby "
"mute step spotless scrape explain used carpenter heavy argument bump paste feigned coherent driving stroke separate tenuous "
"letters analyze unarmed bawdy different absurd six hurt shame fast pour church vague real whole";


#endif /* _WORDS1000_H_ */
