#line 1 "Grammar2.lex.c"

#line 3 "Grammar2.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define Grammar2_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer Grammar2_create_buffer
#endif

#ifdef yy_delete_buffer
#define Grammar2_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer Grammar2_delete_buffer
#endif

#ifdef yy_scan_buffer
#define Grammar2_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer Grammar2_scan_buffer
#endif

#ifdef yy_scan_string
#define Grammar2_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string Grammar2_scan_string
#endif

#ifdef yy_scan_bytes
#define Grammar2_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes Grammar2_scan_bytes
#endif

#ifdef yy_init_buffer
#define Grammar2_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer Grammar2_init_buffer
#endif

#ifdef yy_flush_buffer
#define Grammar2_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer Grammar2_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define Grammar2_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state Grammar2_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define Grammar2_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer Grammar2_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define Grammar2push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state Grammar2push_buffer_state
#endif

#ifdef yypop_buffer_state
#define Grammar2pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state Grammar2pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define Grammar2ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack Grammar2ensure_buffer_stack
#endif

#ifdef yylex
#define Grammar2lex_ALREADY_DEFINED
#else
#define yylex Grammar2lex
#endif

#ifdef yyrestart
#define Grammar2restart_ALREADY_DEFINED
#else
#define yyrestart Grammar2restart
#endif

#ifdef yylex_init
#define Grammar2lex_init_ALREADY_DEFINED
#else
#define yylex_init Grammar2lex_init
#endif

#ifdef yylex_init_extra
#define Grammar2lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra Grammar2lex_init_extra
#endif

#ifdef yylex_destroy
#define Grammar2lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy Grammar2lex_destroy
#endif

#ifdef yyget_debug
#define Grammar2get_debug_ALREADY_DEFINED
#else
#define yyget_debug Grammar2get_debug
#endif

#ifdef yyset_debug
#define Grammar2set_debug_ALREADY_DEFINED
#else
#define yyset_debug Grammar2set_debug
#endif

#ifdef yyget_extra
#define Grammar2get_extra_ALREADY_DEFINED
#else
#define yyget_extra Grammar2get_extra
#endif

#ifdef yyset_extra
#define Grammar2set_extra_ALREADY_DEFINED
#else
#define yyset_extra Grammar2set_extra
#endif

#ifdef yyget_in
#define Grammar2get_in_ALREADY_DEFINED
#else
#define yyget_in Grammar2get_in
#endif

#ifdef yyset_in
#define Grammar2set_in_ALREADY_DEFINED
#else
#define yyset_in Grammar2set_in
#endif

#ifdef yyget_out
#define Grammar2get_out_ALREADY_DEFINED
#else
#define yyget_out Grammar2get_out
#endif

#ifdef yyset_out
#define Grammar2set_out_ALREADY_DEFINED
#else
#define yyset_out Grammar2set_out
#endif

#ifdef yyget_leng
#define Grammar2get_leng_ALREADY_DEFINED
#else
#define yyget_leng Grammar2get_leng
#endif

#ifdef yyget_text
#define Grammar2get_text_ALREADY_DEFINED
#else
#define yyget_text Grammar2get_text
#endif

#ifdef yyget_lineno
#define Grammar2get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno Grammar2get_lineno
#endif

#ifdef yyset_lineno
#define Grammar2set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno Grammar2set_lineno
#endif

#ifdef yyget_column
#define Grammar2get_column_ALREADY_DEFINED
#else
#define yyget_column Grammar2get_column
#endif

#ifdef yyset_column
#define Grammar2set_column_ALREADY_DEFINED
#else
#define yyset_column Grammar2set_column
#endif

#ifdef yywrap
#define Grammar2wrap_ALREADY_DEFINED
#else
#define yywrap Grammar2wrap
#endif

#ifdef yyget_lval
#define Grammar2get_lval_ALREADY_DEFINED
#else
#define yyget_lval Grammar2get_lval
#endif

#ifdef yyset_lval
#define Grammar2set_lval_ALREADY_DEFINED
#else
#define yyset_lval Grammar2set_lval
#endif

#ifdef yyalloc
#define Grammar2alloc_ALREADY_DEFINED
#else
#define yyalloc Grammar2alloc
#endif

#ifdef yyrealloc
#define Grammar2realloc_ALREADY_DEFINED
#else
#define yyrealloc Grammar2realloc
#endif

#ifdef yyfree
#define Grammar2free_ALREADY_DEFINED
#else
#define yyfree Grammar2free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define Grammar2wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef const struct yy_trans_info *yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 13
#define YY_END_OF_BUFFER 14
struct yy_trans_info
	{
	flex_int16_t yy_verify;
	flex_int16_t yy_nxt;
	};
static const struct yy_trans_info yy_transition[1995] =
    {
 {   0,   0 }, {   0,1867 }, {   0,   0 }, {   0,1865 }, {   1,1300 },
 {   2,1300 }, {   3,1300 }, {   4,1300 }, {   5,1300 }, {   6,1300 },
 {   7,1300 }, {   8,1300 }, {   9,1300 }, {  10,1302 }, {  11,1300 },
 {  12,1300 }, {  13,1300 }, {  14,1300 }, {  15,1300 }, {  16,1300 },
 {  17,1300 }, {  18,1300 }, {  19,1300 }, {  20,1300 }, {  21,1300 },
 {  22,1300 }, {  23,1300 }, {  24,1300 }, {  25,1300 }, {  26,1300 },
 {  27,1300 }, {  28,1300 }, {  29,1300 }, {  30,1300 }, {  31,1300 },
 {  32,1300 }, {  33,1300 }, {  34,1300 }, {  35,1300 }, {  36,1300 },
 {  37,1300 }, {  38,1300 }, {  39,1300 }, {  40,1300 }, {  41,1300 },
 {  42,1300 }, {  43,1300 }, {  44,1300 }, {  45,1300 }, {  46,1300 },

 {  47,1300 }, {  48,1300 }, {  49,1300 }, {  50,1300 }, {  51,1300 },
 {  52,1300 }, {  53,1300 }, {  54,1300 }, {  55,1300 }, {  56,1300 },
 {  57,1300 }, {  58,1300 }, {  59,1300 }, {  60,1300 }, {  61,1300 },
 {  62,1300 }, {  63,1300 }, {  64,1300 }, {  65,1300 }, {  66,1300 },
 {  67,1300 }, {  68,1300 }, {  69,1300 }, {  70,1300 }, {  71,1300 },
 {  72,1300 }, {  73,1300 }, {  74,1300 }, {  75,1300 }, {  76,1300 },
 {  77,1300 }, {  78,1300 }, {  79,1300 }, {  80,1300 }, {  81,1300 },
 {  82,1300 }, {  83,1300 }, {  84,1300 }, {  85,1300 }, {  86,1300 },
 {  87,1300 }, {  88,1300 }, {  89,1300 }, {  90,1300 }, {  91,1300 },
 {  92,1300 }, {  93,1300 }, {  94,1300 }, {  95,1300 }, {  96,1300 },

 {  97,1300 }, {  98,1300 }, {  99,1300 }, { 100,1300 }, { 101,1300 },
 { 102,1300 }, { 103,1300 }, { 104,1300 }, { 105,1300 }, { 106,1300 },
 { 107,1300 }, { 108,1300 }, { 109,1300 }, { 110,1300 }, { 111,1300 },
 { 112,1300 }, { 113,1300 }, { 114,1300 }, { 115,1300 }, { 116,1300 },
 { 117,1300 }, { 118,1300 }, { 119,1300 }, { 120,1300 }, { 121,1300 },
 { 122,1300 }, { 123,1300 }, { 124,1300 }, { 125,1300 }, { 126,1300 },
 { 127,1300 }, { 128,1300 }, {   0,   0 }, {   0,1735 }, {   1,1170 },
 {   2,1170 }, {   3,1170 }, {   4,1170 }, {   5,1170 }, {   6,1170 },
 {   7,1170 }, {   8,1170 }, {   9,1170 }, {  10,1172 }, {  11,1170 },
 {  12,1170 }, {  13,1170 }, {  14,1170 }, {  15,1170 }, {  16,1170 },

 {  17,1170 }, {  18,1170 }, {  19,1170 }, {  20,1170 }, {  21,1170 },
 {  22,1170 }, {  23,1170 }, {  24,1170 }, {  25,1170 }, {  26,1170 },
 {  27,1170 }, {  28,1170 }, {  29,1170 }, {  30,1170 }, {  31,1170 },
 {  32,1170 }, {  33,1170 }, {  34,1170 }, {  35,1170 }, {  36,1170 },
 {  37,1170 }, {  38,1170 }, {  39,1170 }, {  40,1170 }, {  41,1170 },
 {  42,1170 }, {  43,1170 }, {  44,1170 }, {  45,1170 }, {  46,1170 },
 {  47,1170 }, {  48,1170 }, {  49,1170 }, {  50,1170 }, {  51,1170 },
 {  52,1170 }, {  53,1170 }, {  54,1170 }, {  55,1170 }, {  56,1170 },
 {  57,1170 }, {  58,1170 }, {  59,1170 }, {  60,1170 }, {  61,1170 },
 {  62,1170 }, {  63,1170 }, {  64,1170 }, {  65,1170 }, {  66,1170 },

 {  67,1170 }, {  68,1170 }, {  69,1170 }, {  70,1170 }, {  71,1170 },
 {  72,1170 }, {  73,1170 }, {  74,1170 }, {  75,1170 }, {  76,1170 },
 {  77,1170 }, {  78,1170 }, {  79,1170 }, {  80,1170 }, {  81,1170 },
 {  82,1170 }, {  83,1170 }, {  84,1170 }, {  85,1170 }, {  86,1170 },
 {  87,1170 }, {  88,1170 }, {  89,1170 }, {  90,1170 }, {  91,1170 },
 {  92,1170 }, {  93,1170 }, {  94,1170 }, {  95,1170 }, {  96,1170 },
 {  97,1170 }, {  98,1170 }, {  99,1170 }, { 100,1170 }, { 101,1170 },
 { 102,1170 }, { 103,1170 }, { 104,1170 }, { 105,1170 }, { 106,1170 },
 { 107,1170 }, { 108,1170 }, { 109,1170 }, { 110,1170 }, { 111,1170 },
 { 112,1170 }, { 113,1170 }, { 114,1170 }, { 115,1170 }, { 116,1170 },

 { 117,1170 }, { 118,1170 }, { 119,1170 }, { 120,1170 }, { 121,1170 },
 { 122,1170 }, { 123,1170 }, { 124,1170 }, { 125,1170 }, { 126,1170 },
 { 127,1170 }, { 128,1170 }, {   0,   0 }, {   0,1605 }, {   1,1044 },
 {   2,1044 }, {   3,1044 }, {   4,1044 }, {   5,1044 }, {   6,1044 },
 {   7,1044 }, {   8,1044 }, {   9,1044 }, {  10,1044 }, {  11,1044 },
 {  12,1044 }, {  13,1044 }, {  14,1044 }, {  15,1044 }, {  16,1044 },
 {  17,1044 }, {  18,1044 }, {  19,1044 }, {  20,1044 }, {  21,1044 },
 {  22,1044 }, {  23,1044 }, {  24,1044 }, {  25,1044 }, {  26,1044 },
 {  27,1044 }, {  28,1044 }, {  29,1044 }, {  30,1044 }, {  31,1044 },
 {  32,1044 }, {  33,1044 }, {  34,1044 }, {  35,1044 }, {  36,1044 },

 {  37,1044 }, {  38,1044 }, {  39,1044 }, {  40,1044 }, {  41,1044 },
 {  42,1046 }, {  43,1044 }, {  44,1044 }, {  45,1044 }, {  46,1044 },
 {  47,1044 }, {  48,1044 }, {  49,1044 }, {  50,1044 }, {  51,1044 },
 {  52,1044 }, {  53,1044 }, {  54,1044 }, {  55,1044 }, {  56,1044 },
 {  57,1044 }, {  58,1044 }, {  59,1044 }, {  60,1044 }, {  61,1044 },
 {  62,1044 }, {  63,1044 }, {  64,1044 }, {  65,1044 }, {  66,1044 },
 {  67,1044 }, {  68,1044 }, {  69,1044 }, {  70,1044 }, {  71,1044 },
 {  72,1044 }, {  73,1044 }, {  74,1044 }, {  75,1044 }, {  76,1044 },
 {  77,1044 }, {  78,1044 }, {  79,1044 }, {  80,1044 }, {  81,1044 },
 {  82,1044 }, {  83,1044 }, {  84,1044 }, {  85,1044 }, {  86,1044 },

 {  87,1044 }, {  88,1044 }, {  89,1044 }, {  90,1044 }, {  91,1044 },
 {  92,1044 }, {  93,1044 }, {  94,1044 }, {  95,1044 }, {  96,1044 },
 {  97,1044 }, {  98,1044 }, {  99,1044 }, { 100,1044 }, { 101,1044 },
 { 102,1044 }, { 103,1044 }, { 104,1044 }, { 105,1044 }, { 106,1044 },
 { 107,1044 }, { 108,1044 }, { 109,1044 }, { 110,1044 }, { 111,1044 },
 { 112,1044 }, { 113,1044 }, { 114,1044 }, { 115,1044 }, { 116,1044 },
 { 117,1044 }, { 118,1044 }, { 119,1044 }, { 120,1044 }, { 121,1044 },
 { 122,1044 }, { 123,1044 }, { 124,1044 }, { 125,1044 }, { 126,1044 },
 { 127,1044 }, { 128,1044 }, {   0,   0 }, {   0,1475 }, {   1, 914 },
 {   2, 914 }, {   3, 914 }, {   4, 914 }, {   5, 914 }, {   6, 914 },

 {   7, 914 }, {   8, 914 }, {   9, 914 }, {  10, 914 }, {  11, 914 },
 {  12, 914 }, {  13, 914 }, {  14, 914 }, {  15, 914 }, {  16, 914 },
 {  17, 914 }, {  18, 914 }, {  19, 914 }, {  20, 914 }, {  21, 914 },
 {  22, 914 }, {  23, 914 }, {  24, 914 }, {  25, 914 }, {  26, 914 },
 {  27, 914 }, {  28, 914 }, {  29, 914 }, {  30, 914 }, {  31, 914 },
 {  32, 914 }, {  33, 914 }, {  34, 914 }, {  35, 914 }, {  36, 914 },
 {  37, 914 }, {  38, 914 }, {  39, 914 }, {  40, 914 }, {  41, 914 },
 {  42, 916 }, {  43, 914 }, {  44, 914 }, {  45, 914 }, {  46, 914 },
 {  47, 914 }, {  48, 914 }, {  49, 914 }, {  50, 914 }, {  51, 914 },
 {  52, 914 }, {  53, 914 }, {  54, 914 }, {  55, 914 }, {  56, 914 },

 {  57, 914 }, {  58, 914 }, {  59, 914 }, {  60, 914 }, {  61, 914 },
 {  62, 914 }, {  63, 914 }, {  64, 914 }, {  65, 914 }, {  66, 914 },
 {  67, 914 }, {  68, 914 }, {  69, 914 }, {  70, 914 }, {  71, 914 },
 {  72, 914 }, {  73, 914 }, {  74, 914 }, {  75, 914 }, {  76, 914 },
 {  77, 914 }, {  78, 914 }, {  79, 914 }, {  80, 914 }, {  81, 914 },
 {  82, 914 }, {  83, 914 }, {  84, 914 }, {  85, 914 }, {  86, 914 },
 {  87, 914 }, {  88, 914 }, {  89, 914 }, {  90, 914 }, {  91, 914 },
 {  92, 914 }, {  93, 914 }, {  94, 914 }, {  95, 914 }, {  96, 914 },
 {  97, 914 }, {  98, 914 }, {  99, 914 }, { 100, 914 }, { 101, 914 },
 { 102, 914 }, { 103, 914 }, { 104, 914 }, { 105, 914 }, { 106, 914 },

 { 107, 914 }, { 108, 914 }, { 109, 914 }, { 110, 914 }, { 111, 914 },
 { 112, 914 }, { 113, 914 }, { 114, 914 }, { 115, 914 }, { 116, 914 },
 { 117, 914 }, { 118, 914 }, { 119, 914 }, { 120, 914 }, { 121, 914 },
 { 122, 914 }, { 123, 914 }, { 124, 914 }, { 125, 914 }, { 126, 914 },
 { 127, 914 }, { 128, 914 }, {   0,   0 }, {   0,1345 }, {   1, 788 },
 {   2, 788 }, {   3, 788 }, {   4, 788 }, {   5, 788 }, {   6, 788 },
 {   7, 788 }, {   8, 788 }, {   9, 788 }, {  10, 790 }, {  11, 788 },
 {  12, 788 }, {  13, 788 }, {  14, 788 }, {  15, 788 }, {  16, 788 },
 {  17, 788 }, {  18, 788 }, {  19, 788 }, {  20, 788 }, {  21, 788 },
 {  22, 788 }, {  23, 788 }, {  24, 788 }, {  25, 788 }, {  26, 788 },

 {  27, 788 }, {  28, 788 }, {  29, 788 }, {  30, 788 }, {  31, 788 },
 {  32, 788 }, {  33, 788 }, {  34, 788 }, {  35, 788 }, {  36, 788 },
 {  37, 788 }, {  38, 788 }, {  39, 788 }, {  40, 788 }, {  41, 788 },
 {  42, 788 }, {  43, 788 }, {  44, 788 }, {  45, 788 }, {  46, 788 },
 {  47, 788 }, {  48, 788 }, {  49, 788 }, {  50, 788 }, {  51, 788 },
 {  52, 788 }, {  53, 788 }, {  54, 788 }, {  55, 788 }, {  56, 788 },
 {  57, 788 }, {  58, 788 }, {  59, 788 }, {  60, 788 }, {  61, 788 },
 {  62, 788 }, {  63, 788 }, {  64, 788 }, {  65, 788 }, {  66, 788 },
 {  67, 788 }, {  68, 788 }, {  69, 788 }, {  70, 788 }, {  71, 788 },
 {  72, 788 }, {  73, 788 }, {  74, 788 }, {  75, 788 }, {  76, 788 },

 {  77, 788 }, {  78, 788 }, {  79, 788 }, {  80, 788 }, {  81, 788 },
 {  82, 788 }, {  83, 788 }, {  84, 788 }, {  85, 788 }, {  86, 788 },
 {  87, 788 }, {  88, 788 }, {  89, 788 }, {  90, 788 }, {  91, 788 },
 {  92, 788 }, {  93, 788 }, {  94, 788 }, {  95, 788 }, {  96, 788 },
 {  97, 788 }, {  98, 788 }, {  99, 788 }, { 100, 788 }, { 101, 788 },
 { 102, 788 }, { 103, 788 }, { 104, 788 }, { 105, 788 }, { 106, 788 },
 { 107, 788 }, { 108, 788 }, { 109, 788 }, { 110, 788 }, { 111, 788 },
 { 112, 788 }, { 113, 788 }, { 114, 788 }, { 115, 788 }, { 116, 788 },
 { 117, 788 }, { 118, 788 }, { 119, 788 }, { 120, 788 }, { 121, 788 },
 { 122, 788 }, { 123, 788 }, { 124, 788 }, { 125, 788 }, { 126, 788 },

 { 127, 788 }, { 128, 788 }, {   0,   0 }, {   0,1215 }, {   1, 658 },
 {   2, 658 }, {   3, 658 }, {   4, 658 }, {   5, 658 }, {   6, 658 },
 {   7, 658 }, {   8, 658 }, {   9, 658 }, {  10, 660 }, {  11, 658 },
 {  12, 658 }, {  13, 658 }, {  14, 658 }, {  15, 658 }, {  16, 658 },
 {  17, 658 }, {  18, 658 }, {  19, 658 }, {  20, 658 }, {  21, 658 },
 {  22, 658 }, {  23, 658 }, {  24, 658 }, {  25, 658 }, {  26, 658 },
 {  27, 658 }, {  28, 658 }, {  29, 658 }, {  30, 658 }, {  31, 658 },
 {  32, 658 }, {  33, 658 }, {  34, 658 }, {  35, 658 }, {  36, 658 },
 {  37, 658 }, {  38, 658 }, {  39, 658 }, {  40, 658 }, {  41, 658 },
 {  42, 658 }, {  43, 658 }, {  44, 658 }, {  45, 658 }, {  46, 658 },

 {  47, 658 }, {  48, 658 }, {  49, 658 }, {  50, 658 }, {  51, 658 },
 {  52, 658 }, {  53, 658 }, {  54, 658 }, {  55, 658 }, {  56, 658 },
 {  57, 658 }, {  58, 658 }, {  59, 658 }, {  60, 658 }, {  61, 658 },
 {  62, 658 }, {  63, 658 }, {  64, 658 }, {  65, 658 }, {  66, 658 },
 {  67, 658 }, {  68, 658 }, {  69, 658 }, {  70, 658 }, {  71, 658 },
 {  72, 658 }, {  73, 658 }, {  74, 658 }, {  75, 658 }, {  76, 658 },
 {  77, 658 }, {  78, 658 }, {  79, 658 }, {  80, 658 }, {  81, 658 },
 {  82, 658 }, {  83, 658 }, {  84, 658 }, {  85, 658 }, {  86, 658 },
 {  87, 658 }, {  88, 658 }, {  89, 658 }, {  90, 658 }, {  91, 658 },
 {  92, 658 }, {  93, 658 }, {  94, 658 }, {  95, 658 }, {  96, 658 },

 {  97, 658 }, {  98, 658 }, {  99, 658 }, { 100, 658 }, { 101, 658 },
 { 102, 658 }, { 103, 658 }, { 104, 658 }, { 105, 658 }, { 106, 658 },
 { 107, 658 }, { 108, 658 }, { 109, 658 }, { 110, 658 }, { 111, 658 },
 { 112, 658 }, { 113, 658 }, { 114, 658 }, { 115, 658 }, { 116, 658 },
 { 117, 658 }, { 118, 658 }, { 119, 658 }, { 120, 658 }, { 121, 658 },
 { 122, 658 }, { 123, 658 }, { 124, 658 }, { 125, 658 }, { 126, 658 },
 { 127, 658 }, { 128, 658 }, {   0,   0 }, {   0,1085 }, {   1, 532 },
 {   2, 532 }, {   3, 532 }, {   4, 532 }, {   5, 532 }, {   6, 532 },
 {   7, 532 }, {   8, 532 }, {   9, 532 }, {  10, 522 }, {  11, 532 },
 {  12, 532 }, {  13, 532 }, {  14, 532 }, {  15, 532 }, {  16, 532 },

 {  17, 532 }, {  18, 532 }, {  19, 532 }, {  20, 532 }, {  21, 532 },
 {  22, 532 }, {  23, 532 }, {  24, 532 }, {  25, 532 }, {  26, 532 },
 {  27, 532 }, {  28, 532 }, {  29, 532 }, {  30, 532 }, {  31, 532 },
 {  32, 532 }, {  33, 532 }, {  34, 532 }, {  35, 534 }, {  36, 532 },
 {  37, 532 }, {  38, 532 }, {  39, 532 }, {  40, 532 }, {  41, 532 },
 {  42, 532 }, {  43, 532 }, {  44, 532 }, {  45, 532 }, {  46, 532 },
 {  47, 536 }, {  48, 532 }, {  49, 532 }, {  50, 532 }, {  51, 532 },
 {  52, 532 }, {  53, 532 }, {  54, 532 }, {  55, 532 }, {  56, 532 },
 {  57, 532 }, {  58, 532 }, {  59, 532 }, {  60, 532 }, {  61, 532 },
 {  62, 532 }, {  63, 532 }, {  64, 532 }, {  65, 532 }, {  66, 532 },

 {  67, 532 }, {  68, 532 }, {  69, 532 }, {  70, 532 }, {  71, 532 },
 {  72, 532 }, {  73, 532 }, {  74, 532 }, {  75, 532 }, {  76, 532 },
 {  77, 532 }, {  78, 532 }, {  79, 532 }, {  80, 532 }, {  81, 532 },
 {  82, 532 }, {  83, 532 }, {  84, 532 }, {  85, 532 }, {  86, 532 },
 {  87, 532 }, {  88, 532 }, {  89, 532 }, {  90, 532 }, {  91, 532 },
 {  92, 532 }, {  93, 532 }, {  94, 532 }, {  95, 532 }, {  96, 532 },
 {  97, 532 }, {  98, 532 }, {  99, 532 }, { 100, 532 }, { 101, 532 },
 { 102, 532 }, { 103, 532 }, { 104, 532 }, { 105, 532 }, { 106, 532 },
 { 107, 532 }, { 108, 532 }, { 109, 532 }, { 110, 532 }, { 111, 532 },
 { 112, 532 }, { 113, 532 }, { 114, 532 }, { 115, 532 }, { 116, 532 },

 { 117, 532 }, { 118, 532 }, { 119, 532 }, { 120, 532 }, { 121, 532 },
 { 122, 532 }, { 123, 532 }, { 124, 532 }, { 125, 532 }, { 126, 532 },
 { 127, 532 }, { 128, 532 }, {   0,   0 }, {   0, 955 }, {   1, 402 },
 {   2, 402 }, {   3, 402 }, {   4, 402 }, {   5, 402 }, {   6, 402 },
 {   7, 402 }, {   8, 402 }, {   9, 402 }, {  10, 392 }, {  11, 402 },
 {  12, 402 }, {  13, 402 }, {  14, 402 }, {  15, 402 }, {  16, 402 },
 {  17, 402 }, {  18, 402 }, {  19, 402 }, {  20, 402 }, {  21, 402 },
 {  22, 402 }, {  23, 402 }, {  24, 402 }, {  25, 402 }, {  26, 402 },
 {  27, 402 }, {  28, 402 }, {  29, 402 }, {  30, 402 }, {  31, 402 },
 {  32, 402 }, {  33, 402 }, {  34, 402 }, {  35, 404 }, {  36, 402 },

 {  37, 402 }, {  38, 402 }, {  39, 402 }, {  40, 402 }, {  41, 402 },
 {  42, 402 }, {  43, 402 }, {  44, 402 }, {  45, 402 }, {  46, 402 },
 {  47, 406 }, {  48, 402 }, {  49, 402 }, {  50, 402 }, {  51, 402 },
 {  52, 402 }, {  53, 402 }, {  54, 402 }, {  55, 402 }, {  56, 402 },
 {  57, 402 }, {  58, 402 }, {  59, 402 }, {  60, 402 }, {  61, 402 },
 {  62, 402 }, {  63, 402 }, {  64, 402 }, {  65, 402 }, {  66, 402 },
 {  67, 402 }, {  68, 402 }, {  69, 402 }, {  70, 402 }, {  71, 402 },
 {  72, 402 }, {  73, 402 }, {  74, 402 }, {  75, 402 }, {  76, 402 },
 {  77, 402 }, {  78, 402 }, {  79, 402 }, {  80, 402 }, {  81, 402 },
 {  82, 402 }, {  83, 402 }, {  84, 402 }, {  85, 402 }, {  86, 402 },

 {  87, 402 }, {  88, 402 }, {  89, 402 }, {  90, 402 }, {  91, 402 },
 {  92, 402 }, {  93, 402 }, {  94, 402 }, {  95, 402 }, {  96, 402 },
 {  97, 402 }, {  98, 402 }, {  99, 402 }, { 100, 402 }, { 101, 402 },
 { 102, 402 }, { 103, 402 }, { 104, 402 }, { 105, 402 }, { 106, 402 },
 { 107, 402 }, { 108, 402 }, { 109, 402 }, { 110, 402 }, { 111, 402 },
 { 112, 402 }, { 113, 402 }, { 114, 402 }, { 115, 402 }, { 116, 402 },
 { 117, 402 }, { 118, 402 }, { 119, 402 }, { 120, 402 }, { 121, 402 },
 { 122, 402 }, { 123, 402 }, { 124, 402 }, { 125, 402 }, { 126, 402 },
 { 127, 402 }, { 128, 402 }, {   0,  10 }, {   0, 825 }, {   1, 347 },
 {   2, 347 }, {   3, 347 }, {   4, 347 }, {   5, 347 }, {   6, 347 },

 {   7, 347 }, {   8, 347 }, {   9, 278 }, {  10, 280 }, {  11, 347 },
 {  12, 347 }, {  13, 347 }, {  14, 347 }, {  15, 347 }, {  16, 347 },
 {  17, 347 }, {  18, 347 }, {  19, 347 }, {  20, 347 }, {  21, 347 },
 {  22, 347 }, {  23, 347 }, {  24, 347 }, {  25, 347 }, {  26, 347 },
 {  27, 347 }, {  28, 347 }, {  29, 347 }, {  30, 347 }, {  31, 347 },
 {  32, 278 }, {  33, 347 }, {  34, 347 }, {  35, 347 }, {  36, 347 },
 {  37, 347 }, {  38, 347 }, {  39, 347 }, {  40, 347 }, {  41, 347 },
 {  42, 347 }, {  43, 347 }, {  44, 347 }, {  45, 347 }, {  46, 347 },
 {  47, 347 }, {  48, 347 }, {  49, 347 }, {  50, 347 }, {  51, 347 },
 {  52, 347 }, {  53, 347 }, {  54, 347 }, {  55, 347 }, {  56, 347 },

 {  57, 347 }, {  58, 347 }, {  59, 347 }, {  60, 347 }, {  61, 347 },
 {  62, 347 }, {  63, 347 }, {  64, 347 }, {  65, 347 }, {  66, 347 },
 {  67, 347 }, {  68, 347 }, {  69, 347 }, {  70, 347 }, {  71, 347 },
 {  72, 347 }, {  73, 347 }, {  74, 347 }, {  75, 347 }, {  76, 347 },
 {  77, 347 }, {  78, 347 }, {  79, 347 }, {  80, 347 }, {  81, 347 },
 {  82, 347 }, {  83, 347 }, {  84, 347 }, {  85, 347 }, {  86, 347 },
 {  87, 347 }, {  88, 347 }, {  89, 347 }, {  90, 347 }, {  91, 347 },
 {  92, 347 }, {  93, 347 }, {  94, 347 }, {  95, 347 }, {  96, 347 },
 {  97, 347 }, {  98, 347 }, {  99, 347 }, { 100, 347 }, { 101, 347 },
 { 102, 347 }, { 103, 347 }, { 104, 347 }, { 105, 347 }, { 106, 347 },

 { 107, 347 }, { 108, 347 }, { 109, 347 }, { 110, 347 }, { 111, 347 },
 { 112, 347 }, { 113, 347 }, { 114, 347 }, { 115, 347 }, { 116, 347 },
 { 117, 347 }, { 118, 347 }, { 119, 347 }, { 120, 347 }, { 121, 347 },
 { 122, 347 }, { 123, 347 }, { 124, 347 }, { 125, 347 }, { 126, 347 },
 { 127, 347 }, { 128, 347 }, {   0,  10 }, {   0, 695 }, {   1, 217 },
 {   2, 217 }, {   3, 217 }, {   4, 217 }, {   5, 217 }, {   6, 217 },
 {   7, 217 }, {   8, 217 }, {   9, 148 }, {  10, 150 }, {  11, 217 },
 {  12, 217 }, {  13, 217 }, {  14, 217 }, {  15, 217 }, {  16, 217 },
 {  17, 217 }, {  18, 217 }, {  19, 217 }, {  20, 217 }, {  21, 217 },
 {  22, 217 }, {  23, 217 }, {  24, 217 }, {  25, 217 }, {  26, 217 },

 {  27, 217 }, {  28, 217 }, {  29, 217 }, {  30, 217 }, {  31, 217 },
 {  32, 148 }, {  33, 217 }, {  34, 217 }, {  35, 217 }, {  36, 217 },
 {  37, 217 }, {  38, 217 }, {  39, 217 }, {  40, 217 }, {  41, 217 },
 {  42, 217 }, {  43, 217 }, {  44, 217 }, {  45, 217 }, {  46, 217 },
 {  47, 217 }, {  48, 217 }, {  49, 217 }, {  50, 217 }, {  51, 217 },
 {  52, 217 }, {  53, 217 }, {  54, 217 }, {  55, 217 }, {  56, 217 },
 {  57, 217 }, {  58, 217 }, {  59, 217 }, {  60, 217 }, {  61, 217 },
 {  62, 217 }, {  63, 217 }, {  64, 217 }, {  65, 217 }, {  66, 217 },
 {  67, 217 }, {  68, 217 }, {  69, 217 }, {  70, 217 }, {  71, 217 },
 {  72, 217 }, {  73, 217 }, {  74, 217 }, {  75, 217 }, {  76, 217 },

 {  77, 217 }, {  78, 217 }, {  79, 217 }, {  80, 217 }, {  81, 217 },
 {  82, 217 }, {  83, 217 }, {  84, 217 }, {  85, 217 }, {  86, 217 },
 {  87, 217 }, {  88, 217 }, {  89, 217 }, {  90, 217 }, {  91, 217 },
 {  92, 217 }, {  93, 217 }, {  94, 217 }, {  95, 217 }, {  96, 217 },
 {  97, 217 }, {  98, 217 }, {  99, 217 }, { 100, 217 }, { 101, 217 },
 { 102, 217 }, { 103, 217 }, { 104, 217 }, { 105, 217 }, { 106, 217 },
 { 107, 217 }, { 108, 217 }, { 109, 217 }, { 110, 217 }, { 111, 217 },
 { 112, 217 }, { 113, 217 }, { 114, 217 }, { 115, 217 }, { 116, 217 },
 { 117, 217 }, { 118, 217 }, { 119, 217 }, { 120, 217 }, { 121, 217 },
 { 122, 217 }, { 123, 217 }, { 124, 217 }, { 125, 217 }, { 126, 217 },

 { 127, 217 }, { 128, 217 }, {   0,   1 }, {   0, 565 }, {   0,  13 },
 {   0, 563 }, {   0,   3 }, {   0, 561 }, {   0,   3 }, {   0, 559 },
 {   0,   5 }, {   0, 557 }, {   0,   4 }, {   0, 555 }, {   0,   9 },
 {   0, 553 }, {   0,   9 }, {   0, 551 }, {   0,   9 }, {   0, 549 },
 {   0,  10 }, {   0, 547 }, {   0,  12 }, {   0, 545 }, {   0,   2 },
 {   0, 543 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   9, 205 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  32, 205 }, {   0,   0 },
 {   0,   0 }, {  47,  16 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  42, 203 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  47, 205 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,  11 },
 {   0, 478 }, {   1, 208 }, {   2, 208 }, {   3, 208 }, {   4, 208 },
 {   5, 208 }, {   6, 208 }, {   7, 208 }, {   8, 208 }, {   0,   0 },

 {   0,   0 }, {  11, 208 }, {  12, 208 }, {  13, 208 }, {  14, 208 },
 {  15, 208 }, {  16, 208 }, {  17, 208 }, {  18, 208 }, {  19, 208 },
 {  20, 208 }, {  21, 208 }, {  22, 208 }, {  23, 208 }, {  24, 208 },
 {  25, 208 }, {  26, 208 }, {  27, 208 }, {  28, 208 }, {  29, 208 },
 {  30, 208 }, {  31, 208 }, { 105, 203 }, {  33, 208 }, {  34, 208 },
 {  35, 208 }, {  36, 208 }, {  37, 208 }, {  38, 208 }, {  39, 208 },
 {  40, 208 }, {  41, 208 }, {  42, 208 }, {  43, 208 }, {  44, 208 },
 {  45, 208 }, {  46, 208 }, {  47, 208 }, {  48, 208 }, {  49, 208 },
 {  50, 208 }, {  51, 208 }, {  52, 208 }, {  53, 208 }, {  54, 208 },
 {  55, 208 }, {  56, 208 }, {  57, 208 }, {  58, 208 }, {  59, 208 },

 {  60, 208 }, {  61, 208 }, {  62, 208 }, {  63, 208 }, {  64, 208 },
 {  65, 208 }, {  66, 208 }, {  67, 208 }, {  68, 208 }, {  69, 208 },
 {  70, 208 }, {  71, 208 }, {  72, 208 }, {  73, 208 }, {  74, 208 },
 {  75, 208 }, {  76, 208 }, {  77, 208 }, {  78, 208 }, {  79, 208 },
 {  80, 208 }, {  81, 208 }, {  82, 208 }, {  83, 208 }, {  84, 208 },
 {  85, 208 }, {  86, 208 }, {  87, 208 }, {  88, 208 }, {  89, 208 },
 {  90, 208 }, {  91, 208 }, {  92, 208 }, {  93, 208 }, {  94, 208 },
 {  95, 208 }, {  96, 208 }, {  97, 208 }, {  98, 208 }, {  99, 208 },
 { 100, 208 }, { 101, 208 }, { 102, 208 }, { 103, 208 }, { 104, 208 },
 { 105, 208 }, { 106, 208 }, { 107, 208 }, { 108, 208 }, { 109, 208 },

 { 110, 208 }, { 111, 208 }, { 112, 208 }, { 113, 208 }, { 114, 208 },
 { 115, 208 }, { 116, 208 }, { 117, 208 }, { 118, 208 }, { 119, 208 },
 { 120, 208 }, { 121, 208 }, { 122, 208 }, { 123, 208 }, { 124, 208 },
 { 125, 208 }, { 126, 208 }, { 127, 208 }, { 128, 208 }, {   0,   0 },
 {   0, 348 }, {   0,   7 }, {   0, 346 }, {   0,   8 }, {   0, 344 },
 {   0,  10 }, {   0, 342 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   9,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  32,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,  11 }, {   0, 270 }, {   1,   0 },

 {   2,   0 }, {   3,   0 }, {   4,   0 }, {   5,   0 }, {   6,   0 },
 {   7,   0 }, {   8,   0 }, {   0,   0 }, {   0,   0 }, {  11,   0 },
 {  12,   0 }, {  13,   0 }, {  14,   0 }, {  15,   0 }, {  16,   0 },
 {  17,   0 }, {  18,   0 }, {  19,   0 }, {  20,   0 }, {  21,   0 },
 {  22,   0 }, {  23,   0 }, {  24,   0 }, {  25,   0 }, {  26,   0 },
 {  27,   0 }, {  28,   0 }, {  29,   0 }, {  30,   0 }, {  31,   0 },
 { 110, 208 }, {  33,   0 }, {  34,   0 }, {  35,   0 }, {  36,   0 },
 {  37,   0 }, {  38,   0 }, {  39,   0 }, {  40,   0 }, {  41,   0 },
 {  42,   0 }, {  43,   0 }, {  44,   0 }, {  45,   0 }, {  46,   0 },
 {  47,   0 }, {  48,   0 }, {  49,   0 }, {  50,   0 }, {  51,   0 },

 {  52,   0 }, {  53,   0 }, {  54,   0 }, {  55,   0 }, {  56,   0 },
 {  57,   0 }, {  58,   0 }, {  59,   0 }, {  60,   0 }, {  61,   0 },
 {  62,   0 }, {  63,   0 }, {  64,   0 }, {  65,   0 }, {  66,   0 },
 {  67,   0 }, {  68,   0 }, {  69,   0 }, {  70,   0 }, {  71,   0 },
 {  72,   0 }, {  73,   0 }, {  74,   0 }, {  75,   0 }, {  76,   0 },
 {  77,   0 }, {  78,   0 }, {  79,   0 }, {  80,   0 }, {  81,   0 },
 {  82,   0 }, {  83,   0 }, {  84,   0 }, {  85,   0 }, {  86,   0 },
 {  87,   0 }, {  88,   0 }, {  89,   0 }, {  90,   0 }, {  91,   0 },
 {  92,   0 }, {  93,   0 }, {  94,   0 }, {  95,   0 }, {  96,   0 },
 {  97,   0 }, {  98,   0 }, {  99,   0 }, { 100,   0 }, { 101,   0 },

 { 102,   0 }, { 103,   0 }, { 104,   0 }, { 105,   0 }, { 106,   0 },
 { 107,   0 }, { 108,   0 }, { 109,   0 }, { 110,   0 }, { 111,   0 },
 { 112,   0 }, { 113,   0 }, { 114,   0 }, { 115,   0 }, { 116,   0 },
 { 117,   0 }, { 118,   0 }, { 119,   0 }, { 120,   0 }, { 121,   0 },
 { 122,   0 }, { 123,   0 }, { 124,   0 }, { 125,   0 }, { 126,   0 },
 { 127,   0 }, { 128,   0 }, {   0,   0 }, {   0, 140 }, {   0,   0 },
 {   0, 138 }, {   0,   0 }, {   0, 136 }, {   0,   0 }, {   0, 134 },
 {   0,   0 }, {   0, 132 }, {   0,   6 }, {   0, 130 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  99,   2 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, { 100,   2 },
 {   0,   0 }, {   0,   0 }, { 101,   2 }, { 108,   2 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, { 117,   2 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, { 129,  14 }, {   1,   0 },    };

static const struct yy_trans_info *yy_start_state_list[11] =
    {
    &yy_transition[1],
    &yy_transition[3],
    &yy_transition[133],
    &yy_transition[263],
    &yy_transition[393],
    &yy_transition[523],
    &yy_transition[653],
    &yy_transition[783],
    &yy_transition[913],
    &yy_transition[1043],
    &yy_transition[1173],

    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "Grammar2.l"
#line 2 "Grammar2.l"
#include <stdio.h>
#include "Grammar2.h"
#include "SdbRequest.h"
#include "Memory.h"
#include "Error.h"

#include "Grammar2.parse.h"
#define YY_DECL int Grammar2_lex(YYSTYPE * yylval_param, void * yyscanner, Grammar2 * grammar)
#define YY_NO_INPUT

/* TODO: Define YY_USER_INIT */
/* TODO: Define YY_USER_ACTION */

void count(void * yyscanner);
unsigned int read_include(void * yyscanner, Grammar2 * grammar);
int end_of_file(void * yyscanner);
YY_BUFFER_STATE get_current_buffer(void * yyscanner);
void pop_buffer(void * yyscanner);
void push_buffer(YY_BUFFER_STATE new_buffer, void * yyscanner);
int get_buffer_top(void * yyscanner);
#line 1030 "Grammar2.lex.c"
/* Defintions of states */

/* Definitions */
/* Rules */
#line 1035 "Grammar2.lex.c"

#define INITIAL 0
#define IN_ML_COMMENT 1
#define IN_SL_COMMENT 2
#define IN_CODE 3
#define IN_INCLUDE 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#ifndef WIN32
#include <unistd.h>
#else
#include <io.h>
#endif
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  , yyscan_t yyscanner);
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

    static void yy_push_state ( int _new_state , yyscan_t yyscanner);
    
    static void yy_pop_state ( yyscan_t yyscanner );
    
    static int yy_top_state ( yyscan_t yyscanner );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	errno=0; \
	while ( (result = (int) read( fileno(yyin), buf, (yy_size_t) max_size )) < 0 ) \
    //WIN32: while ( (result = (int) _read( _fileno(yyin), buf, (yy_size_t) max_size )) < 0 ) \
	{ \
		if( errno != EINTR) \
		{ \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
			break; \
		} \
		errno=0; \
		clearerr(yyin); \
	}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 39 "Grammar2.l"

#line 1305 "Grammar2.lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start_state_list[yyg->yy_start];
yy_match:
		{
		const struct yy_trans_info *yy_trans_info;

		YY_CHAR yy_c;

		for ( yy_c = YY_SC_TO_UI(*yy_cp);
		      (yy_trans_info = &yy_current_state[yy_c])->
		yy_verify == yy_c;
		      yy_c = YY_SC_TO_UI(*++yy_cp) )
			{
			yy_current_state += yy_trans_info->yy_nxt;

			if ( yy_current_state[-1].yy_nxt )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			}
		}

yy_find_action:
		yy_act = yy_current_state[-1].yy_nxt;

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos + 1;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case YY_STATE_EOF(INITIAL):
#line 41 "Grammar2.l"
{
                  Error_new(ERROR_DBG,"<INITIAL> EOF\n");
                  if (get_buffer_top(yyscanner) == 0)
				  {
				    Error_new(ERROR_DBG, "Terminate\n");		
					yyterminate();
				  }
				  else
				  {
                    Grammar2_returnToFile(grammar);
				    pop_buffer(yyscanner);
				  }
				}
	YY_BREAK
case 1:
YY_RULE_SETUP
#line 54 "Grammar2.l"
{
                  yyless(yyleng-1);
				  yy_push_state(IN_CODE, yyscanner);
				}  
	YY_BREAK


case 2:
YY_RULE_SETUP
#line 61 "Grammar2.l"
{
				  yy_pop_state(yyscanner); 
				  return COMMENT;
				}
	YY_BREAK
case YY_STATE_EOF(IN_ML_COMMENT):
#line 65 "Grammar2.l"
{
				  Error_new(ERROR_DBG,"<IN_ML_COMMENT> EOF\n");
				  yyterminate();
				}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 69 "Grammar2.l"
Grammar2_addToBuffer(grammar, yyget_text(yyscanner));
	YY_BREAK


case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 73 "Grammar2.l"
{
				  yy_pop_state(yyscanner); 
                  
				  return COMMENT;
				}
	YY_BREAK
case YY_STATE_EOF(IN_SL_COMMENT):
#line 78 "Grammar2.l"
{
                  Error_new(ERROR_DBG,"<IN_SL_COMMENT> EOF\n"); 
				  yy_pop_state(yyscanner); 
				  return COMMENT;
				}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 83 "Grammar2.l"
Grammar2_addToBuffer(grammar, yyget_text(yyscanner));
	YY_BREAK


case 6:
YY_RULE_SETUP
#line 87 "Grammar2.l"
{ 
				  yy_push_state(IN_INCLUDE,yyscanner);
				  return CODE;
				}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 91 "Grammar2.l"
{
				  yy_push_state(IN_ML_COMMENT, yyscanner);
				  return CODE;
				}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 95 "Grammar2.l"
{
				  yy_push_state(IN_SL_COMMENT, yyscanner);
				  return CODE;
				}
	YY_BREAK
case YY_STATE_EOF(IN_CODE):
#line 99 "Grammar2.l"
{
                  Error_new(ERROR_DBG,"<CODE> EOF\n");
                  yy_push_state(INITIAL, yyscanner);
				  return CODE;
				}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 104 "Grammar2.l"
{
                  //printf("c=%x\n", *yytext);
				  Grammar2_addToBuffer(grammar, yyget_text(yyscanner));
			    }
	YY_BREAK


case 10:
YY_RULE_SETUP
#line 111 "Grammar2.l"

	YY_BREAK
case YY_STATE_EOF(IN_INCLUDE):
#line 112 "Grammar2.l"
{
                  Error_new(ERROR_DBG, "EOF6\n"); yyterminate();
				}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 115 "Grammar2.l"
{
				   read_include(yyscanner, grammar);
				   yy_pop_state(yyscanner);
				}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 119 "Grammar2.l"
//printf("CR!\n");
	YY_BREAK

case 13:
YY_RULE_SETUP
#line 122 "Grammar2.l"
ECHO;
	YY_BREAK
#line 1504 "Grammar2.lex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yy_start_state_list[yyg->yy_start];

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		yy_current_state += yy_current_state[(*yy_cp ? YY_SC_TO_UI(*yy_cp) : 128)].yy_nxt;
		if ( yy_current_state[-1].yy_nxt )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	int yy_c = 128;
	const struct yy_trans_info *yy_trans_info;

	yy_trans_info = &yy_current_state[(unsigned int) yy_c];
	yy_current_state += yy_trans_info->yy_nxt;
	yy_is_jam = (yy_trans_info->yy_verify != yy_c);

	if ( ! yy_is_jam )
		{
		if ( yy_current_state[-1].yy_nxt )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		}

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
		// WIN32: b->yy_is_interactive = file ? (_isatty( _fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( yyg->yy_start_stack_ptr >= yyg->yy_start_stack_depth )
		{
		yy_size_t new_size;

		yyg->yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = (yy_size_t) yyg->yy_start_stack_depth * sizeof( int );

		if ( ! yyg->yy_start_stack )
			yyg->yy_start_stack = (int *) yyalloc( new_size , yyscanner );

		else
			yyg->yy_start_stack = (int *) yyrealloc(
					(void *) yyg->yy_start_stack, new_size , yyscanner );

		if ( ! yyg->yy_start_stack )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	yyg->yy_start_stack[yyg->yy_start_stack_ptr++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( --yyg->yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yyg->yy_start_stack[yyg->yy_start_stack_ptr]);
}

    static int yy_top_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	return yyg->yy_start_stack[yyg->yy_start_stack_ptr - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 122 "Grammar2.l"

unsigned int read_include(void * yyscanner, Grammar2 * grammar)
{
  char * c = 0;
  char * name = 0;
  String * fileName = 0; //String_new(0);
  unsigned int i,j = 0;
  unsigned int result = 0;

  YY_BUFFER_STATE curBuf = get_current_buffer(yyscanner);
  char * text = yyget_text(yyscanner);
  i = 0;
  j = 0;
  name =0;
  while (i< Memory_len(text))
  {
    if ((name==0) && ((text[i]=='<')||(text[i]=='"')))
	{
	  name = &text[i];
	  j = i;
	} 
	else if ((name!=0) && ((text[i]=='>')||(text[i]=='"')))
	{
	  j = i - j;
      break;
	}
	i++;
  }
  // Windows End of Line case: \n\r
  //if (text[i-1]=='\r') i=i-1;
  
  Error_new(ERROR_DBG, "Grammar2.lex.c: Include file name =%s\n", text);
  //Error_new(ERROR_DBG,"Length =%d\n", i);
  
  char * buffer = Memory_alloc(j);
  Memory_set(buffer, 0, j);
  Memory_copy(buffer, name+1, j-1);
  
  fileName = String_new(0);
  String_setBuffer(fileName, buffer, 1);
  Error_new(ERROR_DBG,"INCLUDE %s!!!\n", buffer);

  c = Grammar2_processNewFile(grammar, fileName);
  if (c!=0)
  {
    push_buffer(curBuf,yyscanner);
    yy_scan_string(c, yyscanner);
    result = 1;
  }
  else
  {
    Error_new(ERROR_NORMAL,"Grammar2.lex.c: Cannot find %s\n", String_getBuffer(fileName));
    result = 0;
  }
  String_delete(fileName);
  
  return result;
}

void push_buffer(YY_BUFFER_STATE new_buffer, void * yyscanner)
{
  struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
  yypush_buffer_state(new_buffer,yyscanner);
  Error_new(ERROR_DBG, "PUSH State Stack Pointer = %d\n", yyg->yy_start_stack_ptr);
  Error_new(ERROR_DBG, "PUSH State Stack Top = %d\n", yyg->yy_buffer_stack_top);
  Error_new(ERROR_DBG, "PUSH State Stack Max. = %d\n", yyg->yy_buffer_stack_max);
}

void pop_buffer(void * yyscanner)
{
  struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
  yypop_buffer_state(yyscanner);
  Error_new(ERROR_DBG, "POP State Stack Pointer = %d\n", yyg->yy_start_stack_ptr);
  Error_new(ERROR_DBG, "POP State Stack Top = %d\n", yyg->yy_buffer_stack_top);
  Error_new(ERROR_DBG, "POP State Stack Max. = %d\n", yyg->yy_buffer_stack_max);
}

YY_BUFFER_STATE get_current_buffer(void * yyscanner)
{
  struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
  
  if (yyg->yy_buffer_stack)
    return yyg->yy_buffer_stack[yyg->yy_buffer_stack_top];
  else
    return NULL;
}

int get_buffer_top(void * yyscanner)
{
  struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
  
  return yyg->yy_buffer_stack_top;
}
	
int end_of_file(void * yyscanner)
{
  (void)yyunput;
  (void)yy_top_state;
  return 0;
}

//int yywrap(void)
//{
//  return 1;
//}

int column = 0;

void count(void * yyscanner)
{
  int i;
  char * text = yyget_text(yyscanner);

  for (i = 0; text[i] != '\0'; i++)
    if (text[i] == '\n')
      column = 0;
    else if (text[i] == '\t')
      column += 8 - (column % 8);
    else
      column++;

    /*ECHO;*/
}
